version: "3.0"
services:
  lempa:
    image: registry.gitlab.com/aplus-framework/images/lempa:2
    container_name: lempa-app
    working_dir: /var/www/aplus
    volumes:
      - .:/var/www/aplus
    depends_on:
      - mariadb
    ports:
      - "80:80"
      - "443:443"
    #environment:
    #  - PRELOAD=/var/www/aplus/preload.php
    tty: true
  lempa-last:
    image: registry.gitlab.com/aplus-framework/images/lempa:3
    container_name: lempa-app-last
    working_dir: /var/www/aplus
    volumes:
      - .:/var/www/aplus
    depends_on:
      - mariadb
    ports:
      - "80:80"
      - "443:443"
    #environment:
    #  - PRELOAD=/var/www/aplus/preload.php
    tty: true
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: health_code_api
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    container_name: lempa-mariadb
